# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nroGrupo',
            new_name='numeroGrupo',
        ),
    ]
