# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfesoresCursos',
            new_name='ProfesorCurso',
        ),
        migrations.AlterModelOptions(
            name='profesorcurso',
            options={'verbose_name_plural': 'Profesores - Cursos'},
        ),
    ]
