# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfamiliamayor',
            name='telefonoMadre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosfamiliamayor',
            name='telefonoPadre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosfamiliamenor',
            name='telefonoMadre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosfamiliamenor',
            name='telefonoPadre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefonoCelular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefonoFijo',
            field=models.IntegerField(),
        ),
    ]
