# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20160310_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfamiliamayor',
            name='idRegistro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Registro'),
        ),
        migrations.AlterField(
            model_name='datosfamiliamenor',
            name='idRegistro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Registro'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idProfesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Profesor'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idRegistro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Registro'),
        ),
    ]
