# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20160310_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idCurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Curso'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idHorario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Horario'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
