# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20160510_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora',
            new_name='horaInicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='horaFin',
            field=models.TimeField(default=datetime.datetime(2016, 5, 11, 2, 30, 52, 131835, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
