# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 09:06
from __future__ import unicode_literals

import Encubarte.plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_auto_20160510_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.FileField(default=1, upload_to=Encubarte.plataforma.models.Estudiante.url),
            preserve_default=False,
        ),
    ]
