# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '__first__'),
        ('estudiante', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numeroGrupo', models.IntegerField()),
                ('esCerrado', models.BooleanField()),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Curso')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.BooleanField()),
                ('Profesor', models.BooleanField()),
                ('Administrador', models.BooleanField()),
                ('IDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
