# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='IDuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
