# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_auto_20160908_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
