# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20160913_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='LoginComo',
            field=models.CharField(default=b'None', max_length=20),
        ),
    ]
