# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_roles_logincomo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='edadMaxima',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='curso',
            name='edadMinima',
            field=models.IntegerField(default=b'0'),
        ),
    ]
