# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=20)),
                ('IDestudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Correcciones',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('Correcciones', models.BooleanField()),
                ('IDestudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
