# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcciones',
            name='IDestudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='IDestudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
    ]
